sudo: false

language: node_js

node_js:
  - '4.1'

cache:
  directories:
    - node_modules

notifications:
  email:
    on_success: never
    on_failure: never

before_script:
  - npm install -g tsd

script:
 - tsd install
 - npm run compile
 - npm run test
